"""
Visualize a PyTorch autograd computation graph.

Run:
    python autograd_graph_demo.py

Outputs:
    autograd_graph.dot   - Graphviz DOT file
    autograd_graph.svg   - Offline SVG visualization
    autograd_graph.html  - Mermaid graph you can open in a browser
    autograd_graph.png   - PNG visualization, generated by Graphviz or Pillow
"""

from __future__ import annotations

import html
import shutil
import subprocess
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F


OUTPUT_STEM = "autograd_graph"


class TinyClassifier(nn.Module):
    """A tiny network, just large enough to make the graph interesting."""

    def __init__(self) -> None:
        super().__init__()
        self.fc1 = nn.Linear(3, 4)
        self.fc2 = nn.Linear(4, 2)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        hidden = self.fc1(x)
        activated = torch.tanh(hidden)
        logits = self.fc2(activated)
        return logits


def build_example_graph() -> tuple[torch.Tensor, nn.Module]:
    torch.manual_seed(42)

    model = TinyClassifier()
    x = torch.tensor(
        [
            [0.2, -0.4, 1.0],
            [1.5, 0.3, -0.7],
        ],
        requires_grad=True,
    )
    target = torch.tensor([1, 0])

    logits = model(x)
    loss = F.cross_entropy(logits, target)

    print("Forward values")
    print(f"  logits shape: {tuple(logits.shape)}")
    print(f"  loss: {loss.item():.6f}")
    print(f"  loss.grad_fn: {loss.grad_fn}")
    print()

    # Backward populates gradients on leaf tensors such as parameters and x.
    loss.backward()
    print("After backward")
    print(f"  x.grad shape: {tuple(x.grad.shape)}")
    print(f"  fc1.weight.grad shape: {tuple(model.fc1.weight.grad.shape)}")
    print(f"  fc2.weight.grad shape: {tuple(model.fc2.weight.grad.shape)}")
    print()

    return loss, model


def autograd_edges(root: torch.Tensor) -> tuple[dict[int, str], list[tuple[int, int]]]:
    """Traverse root.grad_fn and return graph nodes plus parent -> child edges."""
    if root.grad_fn is None:
        raise ValueError("root tensor has no grad_fn. Did you forget requires_grad=True?")

    nodes: dict[int, str] = {}
    edges: list[tuple[int, int]] = []
    seen: set[int] = set()

    def visit(fn: torch.autograd.Function) -> None:
        node_id = id(fn)
        if node_id in seen:
            return

        seen.add(node_id)
        nodes[node_id] = type(fn).__name__

        for next_fn, _input_index in fn.next_functions:
            if next_fn is None:
                continue
            child_id = id(next_fn)
            nodes[child_id] = type(next_fn).__name__
            edges.append((node_id, child_id))
            visit(next_fn)

    visit(root.grad_fn)
    return nodes, edges


def write_dot(nodes: dict[int, str], edges: list[tuple[int, int]], path: Path) -> None:
    lines = [
        "digraph AutogradGraph {",
        '  rankdir="LR";',
        '  graph [fontname="Consolas"];',
        '  node [shape=box, style="rounded,filled", fillcolor="#f5f7fb", '
        'fontname="Consolas", color="#6b7280"];',
        '  edge [color="#6b7280"];',
    ]

    for node_id, label in nodes.items():
        lines.append(f'  n{node_id} [label="{label}"];')

    for src, dst in edges:
        lines.append(f"  n{src} -> n{dst};")

    lines.append("}")
    path.write_text("\n".join(lines), encoding="utf-8")


def graph_layout(
    nodes: dict[int, str], edges: list[tuple[int, int]]
) -> tuple[int, int, dict[int, tuple[int, int]], tuple[int, int]]:
    children: dict[int, list[int]] = {node_id: [] for node_id in nodes}
    for src, dst in edges:
        children.setdefault(src, []).append(dst)

    root = next(iter(nodes))
    depth: dict[int, int] = {root: 0}
    queue = [root]
    while queue:
        src = queue.pop(0)
        for dst in children.get(src, []):
            next_depth = depth[src] + 1
            if dst not in depth or next_depth < depth[dst]:
                depth[dst] = next_depth
                queue.append(dst)

    levels: dict[int, list[int]] = {}
    for node_id in nodes:
        levels.setdefault(depth.get(node_id, 0), []).append(node_id)

    box_w = 190
    box_h = 44
    gap_x = 70
    gap_y = 24
    margin = 28
    max_level = max(levels)
    max_rows = max(len(level_nodes) for level_nodes in levels.values())
    width = margin * 2 + (max_level + 1) * box_w + max_level * gap_x
    height = margin * 2 + max_rows * box_h + (max_rows - 1) * gap_y

    positions: dict[int, tuple[int, int]] = {}
    for level, level_nodes in levels.items():
        column_height = len(level_nodes) * box_h + (len(level_nodes) - 1) * gap_y
        start_y = margin + (height - margin * 2 - column_height) // 2
        for row, node_id in enumerate(level_nodes):
            x = margin + level * (box_w + gap_x)
            y = start_y + row * (box_h + gap_y)
            positions[node_id] = (x, y)

    return width, height, positions, (box_w, box_h)


def write_svg(nodes: dict[int, str], edges: list[tuple[int, int]], path: Path) -> None:
    """Write a small offline SVG, so the demo works without Graphviz."""
    width, height, positions, (box_w, box_h) = graph_layout(nodes, edges)

    svg: list[str] = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}">',
        "<defs>",
        '<marker id="arrow" markerWidth="10" markerHeight="10" refX="9" refY="3" '
        'orient="auto" markerUnits="strokeWidth">',
        '<path d="M0,0 L0,6 L9,3 z" fill="#64748b" />',
        "</marker>",
        "</defs>",
        '<rect width="100%" height="100%" fill="#f8fafc"/>',
        '<style>text{font-family:Consolas,Menlo,monospace;font-size:13px;fill:#111827}</style>',
    ]

    for src, dst in edges:
        x1, y1 = positions[src]
        x2, y2 = positions[dst]
        svg.append(
            f'<line x1="{x1 + box_w}" y1="{y1 + box_h / 2}" '
            f'x2="{x2}" y2="{y2 + box_h / 2}" stroke="#64748b" '
            'stroke-width="1.5" marker-end="url(#arrow)"/>'
        )

    for node_id, label in nodes.items():
        x, y = positions[node_id]
        svg.append(
            f'<rect x="{x}" y="{y}" width="{box_w}" height="{box_h}" rx="6" '
            'fill="#ffffff" stroke="#cbd5e1"/>'
        )
        svg.append(
            f'<text x="{x + 12}" y="{y + 27}">{html.escape(label)}</text>'
        )

    svg.append("</svg>")
    path.write_text("\n".join(svg), encoding="utf-8")


def write_pillow_png(
    nodes: dict[int, str], edges: list[tuple[int, int]], path: Path
) -> None:
    """Write a PNG without requiring the Graphviz system package."""
    from PIL import Image, ImageDraw, ImageFont

    width, height, positions, (box_w, box_h) = graph_layout(nodes, edges)
    image = Image.new("RGB", (width, height), "#f8fafc")
    draw = ImageDraw.Draw(image)

    try:
        font = ImageFont.truetype("consola.ttf", 13)
    except OSError:
        font = ImageFont.load_default()

    for src, dst in edges:
        x1, y1 = positions[src]
        x2, y2 = positions[dst]
        start = (x1 + box_w, y1 + box_h // 2)
        end = (x2, y2 + box_h // 2)
        draw.line([start, end], fill="#64748b", width=2)

        arrow = [
            (end[0], end[1]),
            (end[0] - 9, end[1] - 5),
            (end[0] - 9, end[1] + 5),
        ]
        draw.polygon(arrow, fill="#64748b")

    for node_id, label in nodes.items():
        x, y = positions[node_id]
        draw.rounded_rectangle(
            [x, y, x + box_w, y + box_h],
            radius=6,
            fill="#ffffff",
            outline="#cbd5e1",
            width=1,
        )
        draw.text((x + 12, y + 15), label, fill="#111827", font=font)

    image.save(path)


def write_mermaid_html(
    nodes: dict[int, str], edges: list[tuple[int, int]], path: Path
) -> None:
    mermaid_lines = ["flowchart LR"]

    for node_id, label in nodes.items():
        safe_label = html.escape(label)
        mermaid_lines.append(f'  n{node_id}["{safe_label}"]')

    for src, dst in edges:
        mermaid_lines.append(f"  n{src} --> n{dst}")

    mermaid = "\n".join(mermaid_lines)
    page = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>PyTorch Autograd Graph</title>
  <script type="module">
    import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";
    mermaid.initialize({{ startOnLoad: true, theme: "neutral" }});
  </script>
  <style>
    body {{
      margin: 0;
      padding: 24px;
      font-family: Segoe UI, Arial, sans-serif;
      background: #f8fafc;
      color: #111827;
    }}
    .wrap {{
      max-width: 1200px;
      margin: 0 auto;
    }}
    h1 {{
      font-size: 24px;
      margin: 0 0 8px;
    }}
    p {{
      margin: 0 0 20px;
      color: #4b5563;
    }}
    .mermaid {{
      padding: 20px;
      background: white;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      overflow: auto;
    }}
  </style>
</head>
<body>
  <div class="wrap">
    <h1>PyTorch Autograd Graph</h1>
    <p>Arrows point from the final loss backward to the operations used to compute gradients.</p>
    <pre class="mermaid">
{mermaid}
    </pre>
  </div>
</body>
</html>
"""
    path.write_text(page, encoding="utf-8")


def try_render_png(dot_path: Path, png_path: Path) -> bool:
    dot_exe = shutil.which("dot")
    if dot_exe is None:
        return False

    subprocess.run(
        [dot_exe, "-Tpng", str(dot_path), "-o", str(png_path)],
        check=True,
    )
    return True


def write_png(nodes: dict[int, str], edges: list[tuple[int, int]], dot_path: Path, png_path: Path) -> str:
    if try_render_png(dot_path, png_path):
        return "Graphviz"

    write_pillow_png(nodes, edges, png_path)
    return "Pillow fallback"


def main() -> None:
    loss, _model = build_example_graph()
    nodes, edges = autograd_edges(loss)

    dot_path = Path(f"{OUTPUT_STEM}.dot")
    svg_path = Path(f"{OUTPUT_STEM}.svg")
    html_path = Path(f"{OUTPUT_STEM}.html")
    png_path = Path(f"{OUTPUT_STEM}.png")

    write_dot(nodes, edges, dot_path)
    write_svg(nodes, edges, svg_path)
    write_mermaid_html(nodes, edges, html_path)

    print("Graph files")
    print(f"  DOT:  {dot_path.resolve()}")
    print(f"  SVG:  {svg_path.resolve()}")
    print(f"  HTML: {html_path.resolve()}")

    png_renderer = write_png(nodes, edges, dot_path, png_path)
    print(f"  PNG:  {png_path.resolve()} ({png_renderer})")


if __name__ == "__main__":
    main()
